export interface Country {
  name: string;
  dialCode: string;
  flag: string;
  code: string;
}

/** Nigeria first, then Africa, then rest-of-world, all alphabetical within groups. */
export const COUNTRIES: Country[] = [
  // ── Africa (priority) ──────────────────────────────────────────────────
  { name: "Nigeria", dialCode: "+234", flag: "🇳🇬", code: "NG" },
  { name: "Algeria", dialCode: "+213", flag: "🇩🇿", code: "DZ" },
  { name: "Angola", dialCode: "+244", flag: "🇦🇴", code: "AO" },
  { name: "Benin", dialCode: "+229", flag: "🇧🇯", code: "BJ" },
  { name: "Botswana", dialCode: "+267", flag: "🇧🇼", code: "BW" },
  { name: "Burkina Faso", dialCode: "+226", flag: "🇧🇫", code: "BF" },
  { name: "Burundi", dialCode: "+257", flag: "🇧🇮", code: "BI" },
  { name: "Cameroon", dialCode: "+237", flag: "🇨🇲", code: "CM" },
  { name: "Cape Verde", dialCode: "+238", flag: "🇨🇻", code: "CV" },
  { name: "Central African Republic", dialCode: "+236", flag: "🇨🇫", code: "CF" },
  { name: "Chad", dialCode: "+235", flag: "🇹🇩", code: "TD" },
  { name: "Comoros", dialCode: "+269", flag: "🇰🇲", code: "KM" },
  { name: "Congo (Brazzaville)", dialCode: "+242", flag: "🇨🇬", code: "CG" },
  { name: "Congo (DRC)", dialCode: "+243", flag: "🇨🇩", code: "CD" },
  { name: "Cote d'Ivoire", dialCode: "+225", flag: "🇨🇮", code: "CI" },
  { name: "Djibouti", dialCode: "+253", flag: "🇩🇯", code: "DJ" },
  { name: "Egypt", dialCode: "+20", flag: "🇪🇬", code: "EG" },
  { name: "Equatorial Guinea", dialCode: "+240", flag: "🇬🇶", code: "GQ" },
  { name: "Eritrea", dialCode: "+291", flag: "🇪🇷", code: "ER" },
  { name: "Eswatini", dialCode: "+268", flag: "🇸🇿", code: "SZ" },
  { name: "Ethiopia", dialCode: "+251", flag: "🇪🇹", code: "ET" },
  { name: "Gabon", dialCode: "+241", flag: "🇬🇦", code: "GA" },
  { name: "Gambia", dialCode: "+220", flag: "🇬🇲", code: "GM" },
  { name: "Ghana", dialCode: "+233", flag: "🇬🇭", code: "GH" },
  { name: "Guinea", dialCode: "+224", flag: "🇬🇳", code: "GN" },
  { name: "Guinea-Bissau", dialCode: "+245", flag: "🇬🇼", code: "GW" },
  { name: "Kenya", dialCode: "+254", flag: "🇰🇪", code: "KE" },
  { name: "Lesotho", dialCode: "+266", flag: "🇱🇸", code: "LS" },
  { name: "Liberia", dialCode: "+231", flag: "🇱🇷", code: "LR" },
  { name: "Libya", dialCode: "+218", flag: "🇱🇾", code: "LY" },
  { name: "Madagascar", dialCode: "+261", flag: "🇲🇬", code: "MG" },
  { name: "Malawi", dialCode: "+265", flag: "🇲🇼", code: "MW" },
  { name: "Mali", dialCode: "+223", flag: "🇲🇱", code: "ML" },
  { name: "Mauritania", dialCode: "+222", flag: "🇲🇷", code: "MR" },
  { name: "Mauritius", dialCode: "+230", flag: "🇲🇺", code: "MU" },
  { name: "Morocco", dialCode: "+212", flag: "🇲🇦", code: "MA" },
  { name: "Mozambique", dialCode: "+258", flag: "🇲🇿", code: "MZ" },
  { name: "Namibia", dialCode: "+264", flag: "🇳🇦", code: "NA" },
  { name: "Niger", dialCode: "+227", flag: "🇳🇪", code: "NE" },
  { name: "Rwanda", dialCode: "+250", flag: "🇷🇼", code: "RW" },
  { name: "Sao Tome and Principe", dialCode: "+239", flag: "🇸🇹", code: "ST" },
  { name: "Senegal", dialCode: "+221", flag: "🇸🇳", code: "SN" },
  { name: "Seychelles", dialCode: "+248", flag: "🇸🇨", code: "SC" },
  { name: "Sierra Leone", dialCode: "+232", flag: "🇸🇱", code: "SL" },
  { name: "Somalia", dialCode: "+252", flag: "🇸🇴", code: "SO" },
  { name: "South Africa", dialCode: "+27", flag: "🇿🇦", code: "ZA" },
  { name: "South Sudan", dialCode: "+211", flag: "🇸🇸", code: "SS" },
  { name: "Sudan", dialCode: "+249", flag: "🇸🇩", code: "SD" },
  { name: "Tanzania", dialCode: "+255", flag: "🇹🇿", code: "TZ" },
  { name: "Togo", dialCode: "+228", flag: "🇹🇬", code: "TG" },
  { name: "Tunisia", dialCode: "+216", flag: "🇹🇳", code: "TN" },
  { name: "Uganda", dialCode: "+256", flag: "🇺🇬", code: "UG" },
  { name: "Zambia", dialCode: "+260", flag: "🇿🇲", code: "ZM" },
  { name: "Zimbabwe", dialCode: "+263", flag: "🇿🇼", code: "ZW" },
  // ── Rest of world (alphabetical) ───────────────────────────────────────
  { name: "Afghanistan", dialCode: "+93", flag: "🇦🇫", code: "AF" },
  { name: "Albania", dialCode: "+355", flag: "🇦🇱", code: "AL" },
  { name: "Andorra", dialCode: "+376", flag: "🇦🇩", code: "AD" },
  { name: "Argentina", dialCode: "+54", flag: "🇦🇷", code: "AR" },
  { name: "Armenia", dialCode: "+374", flag: "🇦🇲", code: "AM" },
  { name: "Australia", dialCode: "+61", flag: "🇦🇺", code: "AU" },
  { name: "Austria", dialCode: "+43", flag: "🇦🇹", code: "AT" },
  { name: "Azerbaijan", dialCode: "+994", flag: "🇦🇿", code: "AZ" },
  { name: "Bahrain", dialCode: "+973", flag: "🇧🇭", code: "BH" },
  { name: "Bangladesh", dialCode: "+880", flag: "🇧🇩", code: "BD" },
  { name: "Belarus", dialCode: "+375", flag: "🇧🇾", code: "BY" },
  { name: "Belgium", dialCode: "+32", flag: "🇧🇪", code: "BE" },
  { name: "Bolivia", dialCode: "+591", flag: "🇧🇴", code: "BO" },
  { name: "Bosnia and Herzegovina", dialCode: "+387", flag: "🇧🇦", code: "BA" },
  { name: "Brazil", dialCode: "+55", flag: "🇧🇷", code: "BR" },
  { name: "Brunei", dialCode: "+673", flag: "🇧🇳", code: "BN" },
  { name: "Bulgaria", dialCode: "+359", flag: "🇧🇬", code: "BG" },
  { name: "Cambodia", dialCode: "+855", flag: "🇰🇭", code: "KH" },
  { name: "Canada", dialCode: "+1", flag: "🇨🇦", code: "CA" },
  { name: "Chile", dialCode: "+56", flag: "🇨🇱", code: "CL" },
  { name: "China", dialCode: "+86", flag: "🇨🇳", code: "CN" },
  { name: "Colombia", dialCode: "+57", flag: "🇨🇴", code: "CO" },
  { name: "Costa Rica", dialCode: "+506", flag: "🇨🇷", code: "CR" },
  { name: "Croatia", dialCode: "+385", flag: "🇭🇷", code: "HR" },
  { name: "Cuba", dialCode: "+53", flag: "🇨🇺", code: "CU" },
  { name: "Cyprus", dialCode: "+357", flag: "🇨🇾", code: "CY" },
  { name: "Czech Republic", dialCode: "+420", flag: "🇨🇿", code: "CZ" },
  { name: "Denmark", dialCode: "+45", flag: "🇩🇰", code: "DK" },
  { name: "Dominican Republic", dialCode: "+1809", flag: "🇩🇴", code: "DO" },
  { name: "Ecuador", dialCode: "+593", flag: "🇪🇨", code: "EC" },
  { name: "El Salvador", dialCode: "+503", flag: "🇸🇻", code: "SV" },
  { name: "Estonia", dialCode: "+372", flag: "🇪🇪", code: "EE" },
  { name: "Finland", dialCode: "+358", flag: "🇫🇮", code: "FI" },
  { name: "France", dialCode: "+33", flag: "🇫🇷", code: "FR" },
  { name: "Georgia", dialCode: "+995", flag: "🇬🇪", code: "GE" },
  { name: "Germany", dialCode: "+49", flag: "🇩🇪", code: "DE" },
  { name: "Greece", dialCode: "+30", flag: "🇬🇷", code: "GR" },
  { name: "Guatemala", dialCode: "+502", flag: "🇬🇹", code: "GT" },
  { name: "Honduras", dialCode: "+504", flag: "🇭🇳", code: "HN" },
  { name: "Hong Kong", dialCode: "+852", flag: "🇭🇰", code: "HK" },
  { name: "Hungary", dialCode: "+36", flag: "🇭🇺", code: "HU" },
  { name: "Iceland", dialCode: "+354", flag: "🇮🇸", code: "IS" },
  { name: "India", dialCode: "+91", flag: "🇮🇳", code: "IN" },
  { name: "Indonesia", dialCode: "+62", flag: "🇮🇩", code: "ID" },
  { name: "Iran", dialCode: "+98", flag: "🇮🇷", code: "IR" },
  { name: "Iraq", dialCode: "+964", flag: "🇮🇶", code: "IQ" },
  { name: "Ireland", dialCode: "+353", flag: "🇮🇪", code: "IE" },
  { name: "Israel", dialCode: "+972", flag: "🇮🇱", code: "IL" },
  { name: "Italy", dialCode: "+39", flag: "🇮🇹", code: "IT" },
  { name: "Jamaica", dialCode: "+1876", flag: "🇯🇲", code: "JM" },
  { name: "Japan", dialCode: "+81", flag: "🇯🇵", code: "JP" },
  { name: "Jordan", dialCode: "+962", flag: "🇯🇴", code: "JO" },
  { name: "Kazakhstan", dialCode: "+7", flag: "🇰🇿", code: "KZ" },
  { name: "Kuwait", dialCode: "+965", flag: "🇰🇼", code: "KW" },
  { name: "Kyrgyzstan", dialCode: "+996", flag: "🇰🇬", code: "KG" },
  { name: "Laos", dialCode: "+856", flag: "🇱🇦", code: "LA" },
  { name: "Latvia", dialCode: "+371", flag: "🇱🇻", code: "LV" },
  { name: "Lebanon", dialCode: "+961", flag: "🇱🇧", code: "LB" },
  { name: "Lithuania", dialCode: "+370", flag: "🇱🇹", code: "LT" },
  { name: "Luxembourg", dialCode: "+352", flag: "🇱🇺", code: "LU" },
  { name: "Malaysia", dialCode: "+60", flag: "🇲🇾", code: "MY" },
  { name: "Maldives", dialCode: "+960", flag: "🇲🇻", code: "MV" },
  { name: "Mexico", dialCode: "+52", flag: "🇲🇽", code: "MX" },
  { name: "Moldova", dialCode: "+373", flag: "🇲🇩", code: "MD" },
  { name: "Mongolia", dialCode: "+976", flag: "🇲🇳", code: "MN" },
  { name: "Montenegro", dialCode: "+382", flag: "🇲🇪", code: "ME" },
  { name: "Myanmar", dialCode: "+95", flag: "🇲🇲", code: "MM" },
  { name: "Nepal", dialCode: "+977", flag: "🇳🇵", code: "NP" },
  { name: "Netherlands", dialCode: "+31", flag: "🇳🇱", code: "NL" },
  { name: "New Zealand", dialCode: "+64", flag: "🇳🇿", code: "NZ" },
  { name: "Nicaragua", dialCode: "+505", flag: "🇳🇮", code: "NI" },
  { name: "North Korea", dialCode: "+850", flag: "🇰🇵", code: "KP" },
  { name: "North Macedonia", dialCode: "+389", flag: "🇲🇰", code: "MK" },
  { name: "Norway", dialCode: "+47", flag: "🇳🇴", code: "NO" },
  { name: "Oman", dialCode: "+968", flag: "🇴🇲", code: "OM" },
  { name: "Pakistan", dialCode: "+92", flag: "🇵🇰", code: "PK" },
  { name: "Palestine", dialCode: "+970", flag: "🇵🇸", code: "PS" },
  { name: "Panama", dialCode: "+507", flag: "🇵🇦", code: "PA" },
  { name: "Paraguay", dialCode: "+595", flag: "🇵🇾", code: "PY" },
  { name: "Peru", dialCode: "+51", flag: "🇵🇪", code: "PE" },
  { name: "Philippines", dialCode: "+63", flag: "🇵🇭", code: "PH" },
  { name: "Poland", dialCode: "+48", flag: "🇵🇱", code: "PL" },
  { name: "Portugal", dialCode: "+351", flag: "🇵🇹", code: "PT" },
  { name: "Qatar", dialCode: "+974", flag: "🇶🇦", code: "QA" },
  { name: "Romania", dialCode: "+40", flag: "🇷🇴", code: "RO" },
  { name: "Russia", dialCode: "+7", flag: "🇷🇺", code: "RU" },
  { name: "Saudi Arabia", dialCode: "+966", flag: "🇸🇦", code: "SA" },
  { name: "Serbia", dialCode: "+381", flag: "🇷🇸", code: "RS" },
  { name: "Singapore", dialCode: "+65", flag: "🇸🇬", code: "SG" },
  { name: "Slovakia", dialCode: "+421", flag: "🇸🇰", code: "SK" },
  { name: "Slovenia", dialCode: "+386", flag: "🇸🇮", code: "SI" },
  { name: "South Korea", dialCode: "+82", flag: "🇰🇷", code: "KR" },
  { name: "Spain", dialCode: "+34", flag: "🇪🇸", code: "ES" },
  { name: "Sri Lanka", dialCode: "+94", flag: "🇱🇰", code: "LK" },
  { name: "Sweden", dialCode: "+46", flag: "🇸🇪", code: "SE" },
  { name: "Switzerland", dialCode: "+41", flag: "🇨🇭", code: "CH" },
  { name: "Syria", dialCode: "+963", flag: "🇸🇾", code: "SY" },
  { name: "Taiwan", dialCode: "+886", flag: "🇹🇼", code: "TW" },
  { name: "Tajikistan", dialCode: "+992", flag: "🇹🇯", code: "TJ" },
  { name: "Thailand", dialCode: "+66", flag: "🇹🇭", code: "TH" },
  { name: "Trinidad and Tobago", dialCode: "+1868", flag: "🇹🇹", code: "TT" },
  { name: "Turkey", dialCode: "+90", flag: "🇹🇷", code: "TR" },
  { name: "Turkmenistan", dialCode: "+993", flag: "🇹🇲", code: "TM" },
  { name: "Ukraine", dialCode: "+380", flag: "🇺🇦", code: "UA" },
  { name: "United Arab Emirates", dialCode: "+971", flag: "🇦🇪", code: "AE" },
  { name: "United Kingdom", dialCode: "+44", flag: "🇬🇧", code: "GB" },
  { name: "United States", dialCode: "+1", flag: "🇺🇸", code: "US" },
  { name: "Uruguay", dialCode: "+598", flag: "🇺🇾", code: "UY" },
  { name: "Uzbekistan", dialCode: "+998", flag: "🇺🇿", code: "UZ" },
  { name: "Venezuela", dialCode: "+58", flag: "🇻🇪", code: "VE" },
  { name: "Vietnam", dialCode: "+84", flag: "🇻🇳", code: "VN" },
  { name: "Yemen", dialCode: "+967", flag: "🇾🇪", code: "YE" },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]; // Nigeria
